packages:
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - svelte-preprocess

overrides:
  "@mcansh/remix-fastify": "workspace:"
  "@remix-run/css-bundle": "latest"
  "@remix-run/dev": "latest"
  "@remix-run/eslint-config": "latest"
  "@remix-run/node": "latest"
  "@remix-run/react": "latest"
  "@remix-run/server-runtime": "latest"
  "@react-router/node": "latest"
  "@react-router/dev": "latest"
  "react-router": "latest"
