packages:
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - svelte-preprocess

overrides:
  "@mcansh/remix-fastify": "workspace:"
  "@remix-run/eslint-config": "latest"
