services:
  - type: web
    plan: free
    runtime: node
    name: remix-fastify
    buildFilter:
      paths:
        - ./examples/playground
        - ./packages/*
    buildCommand: corepack enable && pnpm i && pnpm run build
    startCommand: cd examples/playground && pnpm run start
    envVars:
      - key: SESSION_SECRET
        generateValue: true

  - type: web
    plan: free
    runtime: node
    name: remix-fastify-basic
    buildFilter:
      paths:
        - ./examples/basic
        - ./packages/*
    buildCommand: corepack enable && pnpm i && pnpm run build
    startCommand: cd examples/basic && pnpm run start

  - type: web
    plan: free
    runtime: node
    name: remix-fastify-vite
    buildFilter:
      paths:
        - ./examples/vite
        - ./packages/*
    buildCommand: corepack enable && pnpm i && pnpm run build
    startCommand: cd examples/vite && pnpm run start
