services:
  - type: web
    name: remix-fastify
    plan: free
    runtime: node
    rootDir: examples/playground
    buildFilter:
      paths:
        - ./packages/**/*
    buildCommand: corepack enable && pnpm i && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: SESSION_SECRET
        generateValue: true

  - type: web
    name: remix-fastify-basic
    plan: free
    runtime: node
    rootDir: examples/basic
    buildFilter:
      paths:
        - ./packages/**/*
    buildCommand: corepack enable && pnpm i && pnpm run build
    startCommand: pnpm run start

  - type: web
    name: remix-fastify-vite
    plan: free
    runtime: node
    rootDir: examples/vite
    buildFilter:
      paths:
        - ./packages/**/*
    buildCommand: corepack enable && pnpm i && pnpm run build
    startCommand: pnpm run start
