services:
  - type: web
    name: remix-fastify
    plan: free
    runtime: node
    rootDir: ./examples/basic
    buildFilter:
      paths:
        - ./examples/basic
        - ./packages/**/*
    buildCommand: npm i -g corepack@latest && corepack enable && pnpm i && pnpm run build
    startCommand: pnpm run start
