import type {
  AppLoadContext,
  UNSAFE_MiddlewareEnabled as MiddlewareEnabled,
  RouterContextProvider,
} from "react-router";

import type {
  HttpServer,
  GetLoadContextFunction as SharedGetLoadContextFunction,
} from "../shared-server.ts";
export type { RequestHandler } from "../shared-server.ts";
export { createReactRouterRequestHandler } from "./server.ts";

/** @deprecated this function has been renamed to createReactRouterRequestHandler */
export { createReactRouterRequestHandler as createRequestHandler } from "./server.ts";
export { reactRouterFastify } from "./plugin.ts";
export type { ReactRouterFastifyOptions } from "./plugin.ts";

type MaybePromise<T> = T | Promise<T>;

/**
 * A function that returns the value to use as `context` in route `loader` and
 * `action` functions.
 *
 * You can think of this as an escape hatch that allows you to pass
 * environment/platform-specific values through to your loader/action, such as
 * values that are generated by Express middleware like `req.session`.
 */
export type GetLoadContextFunction<Server extends HttpServer> =
  SharedGetLoadContextFunction<
    Server,
    MiddlewareEnabled extends true
      ? MaybePromise<RouterContextProvider>
      : MaybePromise<AppLoadContext>
  >;
