import type * as http from "node:http";
import type * as http2 from "node:http2";
import type * as https from "node:https";

import { createReadableStreamFromReadable } from "@react-router/node";
import type {
  FastifyReply,
  FastifyRequest,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RouteGenericInterface,
} from "fastify";
import type {
  AppLoadContext,
  RouterContextProvider,
  ServerBuild,
  UNSAFE_MiddlewareEnabled as MiddlewareEnabled,
} from "react-router";
import { createRequestHandler as createReactRouterRequestHandlerImpl } from "react-router";

type MaybePromise<T> = T | Promise<T>;

export type HttpServer =
  | http.Server
  | https.Server
  | http2.Http2Server
  | http2.Http2SecureServer;

export type HttpRequest = RawRequestDefaultExpression<HttpServer>;
export type HttpResponse = RawReplyDefaultExpression<HttpServer>;

export type RequestHandler<Server extends HttpServer = HttpServer> = (
  request: FastifyRequest<RouteGenericInterface, Server>,
  reply: FastifyReply<RouteGenericInterface, Server>,
) => Promise<void>;

/**
 * A function that returns the value to use as `context` in route `loader` and
 * `action` functions.
 *
 * You can think of this as an escape hatch that allows you to pass
 * environment/platform-specific values through to your loader/action, such as
 * values generated by Fastify hooks/decorators (e.g. `request.session`).
 *
 * When the `v8_middleware` future flag is enabled this must return a
 * `RouterContextProvider`; otherwise it returns your augmented `AppLoadContext`.
 */
export type GetLoadContextFunction<Server extends HttpServer = HttpServer> = (
  request: FastifyRequest<RouteGenericInterface, Server>,
  reply: FastifyReply<RouteGenericInterface, Server>,
) => MiddlewareEnabled extends true
  ? MaybePromise<RouterContextProvider>
  : MaybePromise<AppLoadContext>;

/**
 * Returns a request handler for Fastify that serves the response using React
 * Router.
 */
export function createReactRouterRequestHandler<
  Server extends HttpServer = HttpServer,
>({
  build,
  getLoadContext,
  mode = process.env.NODE_ENV,
}: {
  build: ServerBuild | (() => ServerBuild | Promise<ServerBuild>);
  getLoadContext?: GetLoadContextFunction<Server>;
  mode?: string;
}): RequestHandler<Server> {
  let handleRequest = createReactRouterRequestHandlerImpl(build, mode);

  return async (request, reply) => {
    let request_ = createReactRouterRequest(request, reply);
    let loadContext = await getLoadContext?.(request, reply);
    let response = await handleRequest(request_, loadContext);
    return sendResponse(reply, response);
  };
}

export function createHeaders(
  requestHeaders: FastifyRequest["headers"],
): Headers {
  let headers = new Headers();

  for (let [key, values] of Object.entries(requestHeaders)) {
    // Skip HTTP/2 pseudo-headers (`:method`, `:path`, `:authority`, `:scheme`).
    // Node exposes them on `request.headers`, but `:` is not a valid Fetch
    // header name, so `Headers` would throw on them.
    if (key[0] === ":") continue;
    if (values) {
      if (Array.isArray(values)) {
        for (let value of values) {
          headers.append(key, value);
        }
      } else {
        headers.set(key, values);
      }
    }
  }

  return headers;
}

export function getUrl<Server extends HttpServer>(
  request: FastifyRequest<RouteGenericInterface, Server>,
): string {
  let origin = `${request.protocol}://${request.host}`;
  // Use `request.originalUrl` so React Router is aware of the full path
  let url = `${origin}${request.originalUrl}`;
  return url;
}

export function createReactRouterRequest<Server extends HttpServer>(
  request: FastifyRequest<RouteGenericInterface, Server>,
  reply: FastifyReply<RouteGenericInterface, Server>,
): Request {
  let url = getUrl(request);

  let controller: AbortController | null = new AbortController();

  let init: RequestInit = {
    method: request.method,
    headers: createHeaders(request.headers),
    signal: controller.signal,
  };

  // Abort action/loaders once we can no longer write a response if we have
  // not yet sent a response (i.e., `close` without `finish`)
  // `finish` -> done rendering the response
  // `close` -> response can no longer be written to
  reply.raw.on("finish", () => (controller = null));
  reply.raw.on("close", () => controller?.abort());

  if (request.method !== "GET" && request.method !== "HEAD") {
    init.body = createReadableStreamFromReadable(request.raw);
    init.duplex = "half";
  }

  return new Request(url, init);
}

/**
 * Hand the web `Response` to Fastify as-is. Fastify 5 natively reads its
 * status, copies the headers (each `Set-Cookie` separately), and streams the
 * web `ReadableStream` body — including the null-body, 204, and 304 cases — so
 * there is nothing to translate by hand.
 */
export async function sendResponse<Server extends HttpServer>(
  reply: FastifyReply<RouteGenericInterface, Server>,
  nodeResponse: Response,
): Promise<void> {
  await reply.send(nodeResponse);
}
