name: 🧹 cleanup caches by a branch

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-slim
    permissions:
      actions: write
      contents: read
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: 🧹 Cleanup
        run: gh cache delete --all --ref "$PR_REF" --repo "$GH_REPO" --succeed-on-no-caches
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_REF: refs/pull/${{ github.event.pull_request.number }}/merge
