name: 🚀 Release (preview)
on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "!**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Enable corepack
        run: |
          npm i -g corepack@latest
          corepack enable

      - uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: 🏗️ Build
        run: pnpm run build

      - name: 🚀 Publish PR
        run: pnpm exec pkg-pr-new publish --compact './packages/*' --template './examples/*'
