name: 🦋 Changesets Release
on:
  push:
    branches:
      - release
      - "release-*"
      - "!release-experimental"
      - "!release-experimental-*"
      - "!release-manual"
      - "!release-manual-*"

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  select-mode:
    name: 🦋 Changesets Select Mode
    if: github.repository == 'mcansh/remix-fastify'
    runs-on: ubuntu-slim
    outputs:
      mode: ${{ steps.changesets.outputs.mode }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Enable corepack
        run: |
          npm i -g corepack@latest
          corepack enable

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: 🔐 Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: 🟧 Set publish-branch to current branch
        run: |
          echo "publish-branch=$(git branch --show-current)" >> ~/.npmrc

      - name: 🧭 Select mode
        id: changesets
        uses: changesets/action@v1/select-mode

  version:
    name: 🦋 Changesets Version
    if: github.repository == 'mcansh/remix-fastify' && needs.select-mode.outputs.mode == 'version'
    needs: [select-mode]
    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Enable corepack
        run: |
          npm i -g corepack@latest
          corepack enable

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: 🔐 Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: 🟧 Set publish-branch to current branch
        run: |
          echo "publish-branch=$(git branch --show-current)" >> ~/.npmrc

      - name: 🚀 Version
        uses: changesets/action@v1/version
        with:
          script: pnpm run changeset:version
          commit-message: "chore: Update version for release"
          pr-title: "chore: Update version for release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    name: 🦋 Changesets Publish
    if: github.repository == 'mcansh/remix-fastify' && needs.select-mode.outputs.mode == 'publish'
    needs: [select-mode]
    runs-on: ubuntu-slim
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7

      - name: ⎔ Enable corepack
        run: |
          npm i -g corepack@latest
          corepack enable

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: 🔐 Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: 🟧 Set publish-branch to current branch
        run: |
          echo "publish-branch=$(git branch --show-current)" >> ~/.npmrc

      - name: 🚀 Publish
        id: changesets
        uses: changesets/action@v1/publish
        with:
          script: pnpm run changeset:release
          create-github-releases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  comment:
    name: 📝 Comment on issues and pull requests
    if: github.repository == 'mcansh/remix-fastify' && needs.publish.outputs.published == 'true'
    needs: [publish]
    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 📝 Comment on issues
        uses: remix-run/release-comment-action@v0.5.1
        with:
          DIRECTORY_TO_CHECK: "./packages"
          PACKAGE_NAME: "@mcansh/react-router-fastify"
