name: 🧪 Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        # this is limited to string | boolean | number (https://github.community/t/can-action-inputs-be-arrays/16457)
        # but we want to pass an array (os: "[ubuntu-slim, macos-latest, windows-latest]"),
        # so we'll need to manually stringify it for now
        type: string
      node:
        required: true
        # this is limited to string | boolean | number (https://github.community/t/can-action-inputs-be-arrays/16457)
        # but we want to pass an array (node_version: "[18, 20]"),
        # so we'll need to manually stringify it for now
        type: string

permissions:
  contents: read

jobs:
  build:
    name: ⚙️ Build
    runs-on: ubuntu-slim
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Enable corepack
        run: |
          npm i -g corepack@latest --force
          corepack enable

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: 🏗 Build
        run: pnpm run build

  test:
    name: "${{ matrix.os }} | ${{ matrix.node }}"
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.os) }}
        node: ${{ fromJSON(inputs.node) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Enable corepack
        run: |
          npm i -g corepack@latest --force
          corepack enable

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - name: 🧪 Run Tests
        run: pnpm run test
